### PR TITLE
Safari filter rework

### PR DESCRIPTION
**Pull request by Alex-302**
Included Safari filter to Base filter.
Safari filter marked as obsolete.

https://github.com/AdguardTeam/AdguardFilters/pull/30207

### CODE REVIEW

**Comment by AdamWr** [comment]
Should we add `(Obsolete)` to filter's `"name":` or in this case it's not necessary?

**Comment by ameshkov** [comment]
> Should we add `(Obsolete)` to filter's `"name":` or in this case it's not necessary?

I think in this case it's not necessary

**Comment by AdamWr** [comment]
Ok.

**Comment by Mizzick** [comment]
@Alex-302 seems like something is wrong with 
`https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/content_blocker.txt`

**Comment by Alex-302** [comment]
@Mizzick it is in another branch in `AdguardFilters` - `https://github.com/AdguardTeam/AdguardFilters/blob/safari/EnglishFilter/sections/content_blocker.txt`

**Pull request merged**
