### PR TITLE
Added YanFung mobile ads filter #216

### PR DESCRIPTION
**Pull request by Alex-302**
https://github.com/AdguardTeam/FiltersRegistry/issues/216
replaced ChinaList+EasyList(last update in 2014)

### CODE REVIEW

**Comment by Alex-302** [comment]
@AdguardTeam/filters-maintainers

**Comment by AdamWr** [comment]
I'm not sure if this list is obsolete, for example it contains rules with `$rewrite=abp-resource:` and if I'm not wrong, Adblock Plus supports this kind of rules from this year - https://adblockplus.org/releases/adblock-plus-35-for-chrome-firefox-and-opera-released

But as I recall, for some time this list was problematic (it was not available often), so maybe it's okay to remove it.

**Comment by Alex-302** [comment]
> not sure if this list is obsolete

ok, let's compare in a few days
https://gist.github.com/Alex-302/13e4dd5505fa1c5fa25b61193f7f5a14 `[21.10.2019]`

**Comment by ameshkov** [comment]
Guys, the problem seems to be that the maintainer does not change "Last modified" field.

But they do change the "Version" field (august was the last change it seems):
```
! Version: 201908202325
! Title: ChinaList+EasyList(修正)
! ChinaList and EasyList combination subscription
! Last modified: 03 Feb 2014 03:50 UTC
```

**Comment by Alex-302** [comment]
Ok. What we should to do - replace another(which one? What about `Anti-Adblock Killer | Reek`?) or add new filter?

**Comment by ameshkov** [comment]
Replace a different filter list, and remove the obsolete tag from the ChinaList

**Comment by Alex-302** [comment]
> remove the obsolete tag from the ChinaList

https://github.com/AdguardTeam/FiltersRegistry/pull/240

**Pull request closed without merging**
