### PR TITLE
fix wcostream.com

### PR DESCRIPTION
**Pull request by BlazDT**
https://github.com/AdguardTeam/AdguardFilters/issues/44044

### CODE REVIEW

**Comment by Alex-302** [comment]
why not just @@ exclusion?

**Comment by BlazDT** [comment]
I see no harmful content on that path, so imho that rule is useless. Also if user only enables EasyList, it will still be broken unless adding exclusion there too.

**Comment by Alex-302** [comment]
Please check with ABP. If reproduced - better report them.

**Comment by AdamWr** [comment]
What about merging it or adding rule with `$badfilter` as a temporary solution until it will be fixed in `EasyList`?

**Comment by AdamWr** [comment]
I reported it here - https://github.com/easylist/easylist/issues/4285 and added rule with `$badfilter`.

**Comment by AdamWr** [comment]
It has been fixed in EasyList - https://github.com/easylist/easylist/commit/c149555cde19dea11605f35ac3cb6df65ace7126#diff-ce6ade6e52352499cfb347f46c329f9fL505

**Pull request closed without merging**
