### PR TITLE
Moved PeterLowesList to privacy group

### PR DESCRIPTION
**Pull request by jellizaveta**
Moved PeterLowesList to privacy group

### CODE REVIEW

**Review by zloyden — APPROVED** [review]

**Comment by slavaleleka** [comment]
shouldn't we change the description?

**Review by Alex-302 — APPROVED** [review]

**Comment by Alex-302** [comment]
Exclusions/badfiltering from template.txt may be removed, I think so.

**Comment by zloyden** [comment]
> Exclusions/badfiltering from template.txt may be removed(website breakages are not considered a problem by design), I think so.

Well, we can remove them from the template, but if the filter causes too many issues, we should consider disabling it in the future.

**Comment by Alex-302** [comment]
> we should consider disabling it in the future.

I agree.

**Review by Alex-302 — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Pull request merged**
