### PR TITLE
Fix aflamyz.com https://github.com/AdguardTeam/AdguardFilters/issues/35459

### PR DESCRIPTION
**Pull request by Alex-302**

### CODE REVIEW

**Comment by AdamWr** [comment]
It seems that other video players are also broken.

<details><summary>Screenshot</summary>

image

</details>

Maybe we should disable whole rule?
```
$popup,domain=aflamsexnek.com|aflamyz.com|an-online.com|anime2001.com|arabincest.com|cima4up.co|cima4up.tv|e5tsar.com|kora-online.tv|mes001.blogspot.com|movizland.net|movizland.org
```

**Comment by Alex-302** [comment]
@AdamWr it seems this is a bug
https://github.com/AdguardTeam/CoreLibs/issues/1039

**Comment by Alex-302** [comment]
Replaced URL unblocking by rule excluding

**Comment by AdamWr** [comment]
Ok

**Pull request merged**
