### PR TITLE
Added Adblock Thai filter

### PR DESCRIPTION
**Pull request by Alex-302**
https://github.com/adblock-thai/thai-ads-filter

### CODE REVIEW

**Comment by ameshkov** [comment]
Can we replace an old obsolete filter list insstead of adding new?

**Comment by Alex-302** [comment]
Which is better to replace?
<details>

image

</details>

**Comment by ameshkov** [comment]
Whichever you don't like more:)

**Comment by Alex-302** [comment]
done

**Comment by Alex-302** [comment]
Merged.

**Pull request merged**
