### PR TITLE
Fixing broken player

### PR DESCRIPTION
**Pull request by BlazDT**
https://github.com/AdguardTeam/AdguardFilters/issues/31239

### CODE REVIEW

**Comment by Alex-302** [comment]
Is it required for browser extension also?

**Comment by dnmTX** [comment]
As i am the only one who reported that problem,also hard to reproduced by any of you guys,also taking into account that it's a porn site and so far no one came forward to discuss it and i don't use the AG extension because i have the full version.I guess,you guys need to take some leap of faith on this one.
The rule blocks harmless HTML request which will not allow any video to load(on my end):
https://member.hdzog.com/sn4diyux.php   -go visit and see for yourself(it's safe)

**Comment by ameshkov** [comment]
Guys, let's do something with this PR already:)

**Comment by AdamWr** [comment]
Do you mean to merge it?

It seems that it happens only in Slimjet, in other browsers I can't reproduce it.

**Comment by ameshkov** [comment]
Can we replace this rule with something that hides ads and not breaks anything?

**Comment by AdamWr** [comment]
Ok, merged it.
This rule is from EasyList and to be honest I don't have idea what it should blocks.

**Pull request merged**
