### PR TITLE
Re-instating my list after I changed some "!#include" stuff

### PR DESCRIPTION
**Pull request by DandelionSprout**
Presuming that you guys' list build process will go a bit better now. Explained in crucial detail over at https://github.com/AdguardTeam/FiltersCompiler/issues/84.

### CODE REVIEW

**Comment by ameshkov** [comment]
@DandelionSprout it seems that the import process still fails:
```
Building filter: filter_249_NorwegianList
Compiling...
/home/travis/build/AdguardTeam/FiltersRegistry/node_modules/adguard-filters-compiler/index.js:13
        throw error;
        ^
Error: Response status is invalid: 404
    at /home/travis/build/AdguardTeam/FiltersRegistry/node_modules/filters-downloader/src/main/node/file-download-wrapper.js:64:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Alex-302** [comment]
Is not it because of spaces in URL? @tvinzz made changes and 13.06 we tested it, build was succesful.

**Comment by ameshkov** [comment]
@Alex-302 was that version of compiler already merged?

**Comment by Alex-302** [comment]
@ameshkov not merged. On review I guess.

**Comment by ameshkov** [comment]
@Alex-302 okay, let's wait for @tvinzz. When he'll be pull requesting it here, please enable @DandelionSprout filter lists as well.

**Comment by tvinzz** [comment]
fixed and merged: https://github.com/AdguardTeam/FiltersRegistry/pull/353
@DandelionSprout, Norwegian filter is enabled.

**Pull request closed without merging**
