### PR TITLE
AlleBlock - obsolete filter

### PR DESCRIPTION
**Pull request by zloyden**
https://github.com/AdguardTeam/FiltersRegistry/issues/411#issuecomment-1445158649
Seems the filter is really obsolete.

### CODE REVIEW

**Review by piquark6046 — APPROVED** [review]

**Comment by AdamWr** [comment]
Maybe it would be a good idea to change the name too?
To `(Obsolete) AlleBlock`, like in other cases.
https://github.com/AdguardTeam/FiltersRegistry/blob/9ee2c2e05aa11d16537709728cf51207b73f20ff/filters/ThirdParty/filter_245_AlleBlock/metadata.json#L3

**Comment by Alex-302** [comment]
I see applied rules from this filter

<details>
<summary>Details</summary>

image


</details>

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/FiltersRegistry/pull/736#issuecomment-1445865645 sure, added it.
https://github.com/AdguardTeam/FiltersRegistry/pull/736#issuecomment-1445869212 the point is that the filter has not been updated for a long time https://github.com/AdguardTeam/FiltersRegistry/issues/411#issuecomment-1445158649.

**Review by AdamWr — APPROVED** [review]

**Comment by Alex-302** [comment]
> the point is that the filter has not been updated for a long time

Even if the rules are stil working?

**Comment by krystian3w** [comment]
https://www.instalki.pl/aktualnosci/internet/58293-allegro-nowa-strona-glowna-marzec-2023.html


https://www-instalki-pl.translate.goog/aktualnosci/internet/58293-Allegro-poluchil-novuyu-domashnyuyu-stranitsu.-Odni-budut-lyubit-yeye,-drugiye-budut-nenavidet-2023.html?_x_tr_sl=pl&_x_tr_tl=ru&_x_tr_hl=pl

**Pull request merged**
