### PR TITLE
`redirect:` in `exclusions.txt` is too broad

### PR DESCRIPTION
**Pull request by zloyden**
https://github.com/AdguardTeam/FiltersRegistry/issues/636
[Regex](https://regex101.com/r/5DGFet/1)

### CODE REVIEW

**Comment by AdamWr** [comment]
To be honest, I don't know why it have to be excluded, because it's not supported (I'm guessing)?
By the way, what will happens if there will be two (or more) exclamation marks?
Like this:
```
!! Redirect:
!! ! Redirect:
!! !   ! Redirect:
!! !  ! ! Redirect:
```
Should we remove it too?
If so, then maybe something like this will be okay:
```
^!((?:\s*!?)+)(R|r)edirect:
```
Though, I'm not sure if it's needed.

**Comment by zloyden** [comment]
> I don't know why it have to be excluded, because it's not supported

I think the filter build will fail like here https://github.com/AdguardTeam/FiltersCompiler/issues/150.

> By the way, what will happens if there will be two (or more) exclamation marks?

According to [this](https://help.eyeo.com/adblockplus/how-to-write-filters), it also has
```
! Redirect: http://example.com/list.txt
```

**Comment by zloyden** [comment]
> but the question is, what will happens, if it will starts with more than one !?

Actually, it's wrong syntax and I can't check this due to the issue above.
@tvinzz will the build fail in `@AdamWr` case?

**Comment by AdamWr** [comment]
We could also just remove every `[Rr]edirect:` which starts with `!` and I guess it should be okay too.
```
^!.*[Rr]edirect:
```

**Review by Alex-302 — APPROVED** [review]

**Comment by AdamWr** [comment]
Currently we have `Redirect:` and `redirect:`, so as far as I understand, it removes everything which contains this phrase, so I don't think that removing comments (from third-party filters only, if I'm not wrong) is a problem, but okay :)

**Comment by Alex-302** [comment]
> Currently we have `Redirect:` and `redirect:`....

It just hasn't caused any problems yet:)

**Pull request merged**
