### PR TITLE
update compiler to v1.1.96

### PR DESCRIPTION
**Pull request by slavaleleka**
as usual run build and check the report.txt please — previously invalid scriptlet rules should be valid now

### CODE REVIEW

**Comment by AdamWr** [comment]
>! Rule "jeger.pl##+js(set-cookie, _acceptCookies, 1, , reload, 1)" converted to: "jeger.pl#%#//scriptlet('ubo-set-cookie.js', '_acceptCookies', '1', '', 'reload', '1')"

I guess that rules with `reload` as a 4th argument should be converted to `set-cookie-reload` scriptlet.
https://github.com/gorhill/uBlock/wiki/Resources-Library#set-cookiejs-

**Comment by slavaleleka** [comment]
> `set-cookie` rules with `reload` should be converted to `set-cookie-reload`

there is another task for this:
https://github.com/AdguardTeam/FiltersCompiler/issues/181

**Comment by AdamWr** [comment]
Okay, but now it will be converted to "incorrect" rule which I guess will not work how it should.

Another problem is with `offsetExpiresSec` argument, for example:
>! Rule "amway.pl##+js(set-cookie, isAnalyticsCookiesAccepted, false, 1year)" converted to: "amway.pl#%#//scriptlet('ubo-set-cookie.js', 'isAnalyticsCookiesAccepted', 'false', '1year')"

As far as I can see, `offsetExpiresSec` argument is supported only in `trusted-set-cookie`/`trusted-set-cookie-reload` - https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-trusted-scriptlets.md#-%EF%B8%8F-trusted-set-cookie
but not in https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#set-cookie

In `set-cookie` it will be set as a `path`, so it will be probably just ignored.

**Comment by slavaleleka** [comment]
> `#%#//scriptlet('trusted-click-element', ...` are not converted

trusted scriptlets are not supposed to be converted by design

**Comment by AdamWr** [comment]
Okay, so if these issues are planned to be fixed separately, then it looks good to me.

**Review by AdamWr — APPROVED** [review]

**Review by zloyden — APPROVED** [review]

**Pull request merged**
