### PR TITLE
Updated locales from Crowdin

### PR DESCRIPTION
**Pull request by tvinzz**
https://github.com/AdguardTeam/FiltersRegistry/issues/284

### CODE REVIEW

**Comment by lancelot-moon** [comment]
@Mizzick 
@ameshkov 

Your locale zh = zh-CN (Chinese Simplified), which is for China.
zh-TW (Chinese Traditional) is for Taiwan.

But you didn't approve all Chinese Simplified translations in zh-CN.
https://crowdin.com/translate/adguard-applications/17570/en-zhcn

Your Chinese Simplified moderators or Anna need to check translations and then approve them.

**Comment by lancelot-moon** [comment]
I found outmoded English phrase.
https://crowdin.com/translate/adguard-applications/17584/en-en#3863464
Spyware filter reference
-> Tracking Protection filter reference

https://crowdin.com/translate/adguard-applications/17580/en-en#3863318
Mac OS
-> macOS

https://crowdin.com/translate/adguard-applications/17580/en-zhcn#3863308
有用广告过滤器 = Useful filter, which is outmoded.
Your Chinese translators from China need to fix it.

**Comment by lancelot-moon** [comment]
@tvinzz 
Did you also update zh-TW locale?
Please update it.
Thanks.

**Comment by tvinzz** [comment]
@lancelot-moon 
what exact translations do you mean?

**Comment by lancelot-moon** [comment]
@tvinzz 
Did you not read this?
https://github.com/AdguardTeam/FiltersRegistry/pull/292#issuecomment-573603029

Some English phrases were fixed.
I also modified one translation in zh_TW.
But it seems that I don't see you update All locales.
Only some specific locales.
Just remind.
If I misunderstood, sorry.

**Comment by aalpatkina** [comment]
@lancelot-moon we changed 'Spyware filter' to 'Tracking protection filter' and 'Mac OS' to 'macOS' in the English locale. 

I'd like to remind you that you are a Chinese Traditional moderator. There are other moderators for other locales and they make decisions about what and how to change in their translations.

Thank you!

**Comment by ameshkov** [comment]
> we changed 'Spyware filter' to 'Tracking protection filter' and 'Mac OS' to 'macOS' in the English locale.

Do you mean that not every language needs to be changed? I reckon we haven't changed anything in the Russian locale because the translation there reflects the "tracking protection" sense quite okay already.

**Comment by aalpatkina** [comment]
>we changed 'Spyware filter' to 'Tracking protection filter' and 'Mac OS' to 'macOS' in the English locale ...

That was actually my response to this comment: https://github.com/AdguardTeam/FiltersRegistry/pull/292#issuecomment-573603029 

But as about changing the translation of this string 'Spyware filter reference', I think it's not necessary for some locales where the appropriate wording is already in use. 
In fact, I've already updated that string where it was needed and possible.

**Comment by tvinzz** [comment]
Updated in the following pr: https://github.com/AdguardTeam/FiltersRegistry/pull/300

**Pull request closed without merging**
