### PR TITLE
Fix LIste AR location

### PR DESCRIPTION
**Pull request by BlazDT**
Location moved from code.google.com.

### CODE REVIEW

**Comment by Alex-302** [comment]
@AdguardTeam/filters-maintainers please don't miss notifications

**Comment by AdamWr** [comment]
On these websites:
https://adblockplus.org/subscriptions 
https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html
https://filterlists.com/lists/liste-ar
link to `Liste AR` looks like this:
https://easylist-downloads.adblockplus.org/Liste_AR.txt
so maybe we should use it too?
Just asking.

**Comment by BlazDT** [comment]
That one seems to be newer according to date. Though previous website tells the new location is the one I changed to in list.

@smed79
Can you enlighten us please which is the real website and filter list url, thank you.

**Comment by ameshkov** [comment]
Tbh, I think @AdamWr is right, and the proper URL for the filter list is the one on the ABP CDN.

**Comment by smed79** [comment]
> Location moved from code.google.com

August 2015

> which is the real website and filter list url, thank you.

filter list url: https://easylist-downloads.adblockplus.org/Liste_AR.txt
website: https://forums.lanik.us/viewforum.php?f=98

---

FYI, **Liste AR** is supplement subscription for "**Liste_FR+EasyList**" https://issues.adblockplus.org/ticket/4890
https://git.io/vpQK1

**Comment by BlazDT** [comment]
Thank you, modified source :)

**Pull request merged**
