### PR TITLE
Remove add email to account popup from Reddit

### PR DESCRIPTION
**Pull request by PolicyPuma4**

### CODE REVIEW

**Comment by Alex-302** [comment]
They use randomized classes. Is Adguard Annonances enabled?

**Comment by PolicyPuma4** [comment]
> They use randomized classes. Is Adguard Annonances enabled?

Yes, the AdGuard annoyance filter is enabled. While the class seems to be a randomly generated string, it is very much the same for every user, I've tested the filter on multiple browsing sessions and accounts and it works across them all.

**Comment by Alex-302** [comment]
Ok, please show it in dev tools.
I don't know how to reproduce it, with or without account.

**Comment by PolicyPuma4** [comment]
> Ok, please show it in dev tools. I don't know how to reproduce it, with or without account.

This was taken with a clean install of Chrome and I created an account on the spot.

**Comment by Alex-302** [comment]
Oh, this is useful reminder:) I guess they delete not confirmed accounts.

**Pull request closed without merging**
