### PR TITLE
Excluding unsupported options

### PR DESCRIPTION
**Pull request by BlazDT**
There is also the following options, but unsure where to put them:

$1p
$3p
$beacon
$popunder  (from uBlock)

$popunder could maybe rewritten to $popup (if it does the same)

### CODE REVIEW

**Comment by Alex-302** [comment]
```
$1p
$3p
```
these option must be converted on our end.

**Comment by BlazDT** [comment]
Thank you - opened topic for compiler: https://github.com/AdguardTeam/FiltersCompiler/issues/65

**Comment by slavaleleka** [comment]
[FiltersCompiler#65](https://github.com/AdguardTeam/FiltersCompiler/issues/65) is done. is the PR still relevant?

**Comment by ameshkov** [comment]
Seems that it's not

**Pull request closed without merging**
