### PR TITLE
Update locales

### PR DESCRIPTION
**Pull request by Mizzick**

### CODE REVIEW

**Comment by lancelot-moon** [comment]
This midnight, you just uploaded new phrases to Misc/Misc.
http://adguard.oneskyapp.com/collaboration/translate/project/project/119172/language/2#/?keyword=Faroese

#49104735 and #49104736 in Misc/Misc.
I had completed them.
May you update locales again?
Thanks.

**Comment by Mizzick** [comment]
@lancelot-moon thank you!

I will update it again bit later, then more locales will be ready.

**Comment by ameshkov** [comment]
@Mizzick is it time?

**Comment by lancelot-moon** [comment]
@Mizzick

Though only 12 locales 100% finished it on onesky, can't wait...
Even new phrases aren't finished in Russian locale.
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1303
https://github.com/AdguardTeam/AdguardForAndroid/issues/2583

The tag of Faroese language-specific ad blocking can't be correctly shown or localized due to the issue.

**Comment by Mizzick** [comment]
Ready to merge?

**Comment by lancelot-moon** [comment]
Did you ask Andrey or me?
Yes, please.
I guess AG for Android v3.1 will be released.
This should be done first.
Thanks.

**Comment by ameshkov** [comment]
@Mizzick let's merge on monday

**Pull request merged**
