### PR TITLE
Updated compiler and locales

### PR DESCRIPTION
**Pull request by Mizzick**

### CODE REVIEW

**Comment by ameshkov** [comment]
> You have to give translators some time and then update translations.

There are no new strings at all in this commit, just an update from oneskyapp.

> I suggest to modify zh to zh_CN.

This needs to be changed globally in every product, not just here.

**Comment by lancelot-moon** [comment]
> There are no new strings at all in this commit, just an update from oneskyapp.

I mean why AG team modified English phrases and took translations in the same day.
They’re outmoded translations in what you just approved.
You know that you just modify "anti-adblock" to "adblock circumvention" yesterday.
But AG team immediately took the translations yesterday.
Translators have no enough time to fix the translations.
If you want to modify phrases, you can do it early.

**Comment by ameshkov** [comment]
@lancelot-moon ah, missed that. Don't worry, we'll update other translations once they are ready.

**Comment by lancelot-moon** [comment]
Now, only English, Spanish, Polish, Slovenian and Traditional Chinese fix the translations of "adblock circumvention" on onesky.

In Traditional Chinese, now they're the translations of "anti-adblock circumvention/re-injection".
But you modified "anti-adblock circumvention/re-injection" to "adblock circumvention" and soon updated locales in the same day.

Please **anew update the locales** and then apply them in AdGuard products.

**Comment by lancelot-moon** [comment]
@Mizzick

**Comment by ameshkov** [comment]
> May you update translations together?

These are all parts of other AG products and they aren't updated here.

**Pull request merged**
