### PR TITLE
Exclude redundant regex in EasyList China

### PR DESCRIPTION
**Pull request by Yuki2718**
`/\.com\/[0-9a-z]{2}\/[0-9a-z]{2}\/[0-9a-z]{2}\/[0-9a-z]{32}\.js/$script,third-party` in EL China is made redundant by `/^https?:\/\/([a-z0-9]{8,10}\.)?[a-z0-9-]{5,}\.(com|bid|link|online|top|club)\/([a-z0-9]{2}\/){3}[a-f0-9]{32}\.js/$script,third-party` in Base so should be excluded just like done in French list.

### CODE REVIEW

**Comment by Alex-302** [comment]
Does it break something?

**Comment by Yuki2718** [comment]
@Alex-302 No, it's simply redundant.

**Comment by Alex-302** [comment]
I think no need to remove it.

**Comment by Yuki2718** [comment]
> I think no need to remove it.

Despite a similar filter is excluded in French list? I don't get it.

**Comment by Alex-302** [comment]
French is problematic.

**Pull request closed without merging**
