### PR TITLE
AG-29197: change default `expires` for all filters to 5 days

### PR DESCRIPTION
**Pull request by 105th**

### CODE REVIEW

**Comment by slavaleleka** [comment]
why it has to be done?

**Comment by 105th** [comment]
> > increase 'expires' for all extension platforms except safari
> 
> https://uploads.adguard.org/sllh6lf3yrxe9.png

fixed title

**Comment by 105th** [comment]
> why it has to be done?

To implement differential updates and reduce the frequency of full filter downloads

**Review by slavaleleka — APPROVED** [review]

**Review by maximtop — CHANGES_REQUESTED** [review]
для начала нужно на 5 дней сделать

**Review by ameshkov — APPROVED** [review]

**Review by maximtop — APPROVED** [review]

**Pull request merged**
