### PR TITLE
Update compiler to v1.1.93

### PR DESCRIPTION
**Pull request by maximtop**
Update should fix this bug
https://github.com/AdguardTeam/FiltersCompiler/issues/185

### CODE REVIEW

**Review by slavaleleka — APPROVED** [review]

**Comment by Alex-302** [comment]
Wit this version I see the same rule, like in @Yuki2718 comment. 
Which rule is the expected result?

**Comment by maximtop** [comment]
> Wit this version I see the same rule, like in @Yuki2718 comment. Which rule is the expected result?

have you run yarn install before checking?

**Comment by Alex-302** [comment]
> have you run yarn install before checking?

sure

**Comment by Alex-302** [comment]
After `yarn install --force` it works.
Now resulting rule is
`webhostingpost.com##+js(nano-setInterval-booster, \,dataType:_, 1000, 0.02)`

**Pull request merged**
